name: Terraform plan and apply    ##This is optional
on:                     # Not optional(Required)
  workflow_dispatch:    # This is an event to allow workflow to be triggered manually
  push:                 # Define the event that triggers the workflow automatically
    branches:           # Define the target
      - master
      #- test          # This is to show that multiple branches can be targeted for a specific event trigger

  pull_request:
    branches:
      - master 
      #- test          # This is to show that multiple branches can be targeted for a specific event trigger

permissions:            # This will use the token in the code to run
  contents: write
  pull-requests: read
  issues: write

concurrency: Cloudenviroment      # This ensures that only a single workflow will run at a time

# Terraform plan for qa environment
jobs:
  run_plan_in_qa_environment:
    name: terraform init, validate, plan
    uses: ./.github/workflows/reusable_plan_actions.yml
    with:
      ENVIRONMENT_NAME: 'qa'
      TERRAFORM_VERSION: '1.7.2'
      TERRAGRUNT_VERSION: '0.56.0'
      TERRAFORM_WORKING_DIR: ./applied/qa/org_create
      AWS_REGION: 'us-east-1'      
    secrets: inherit

# Terraform apply for qa environment
  run_apply_in_qa_environment:
    name: terraform apply
    #needs: [run_plan_in_qa_environment]      # Check: the first job:plan_in_qa_enviroment must be successful before running apply
    uses: ./.github/workflows/reusable_apply_actions.yml
    with:
      ENVIRONMENT_NAME: 'qa'
      TERRAFORM_VERSION: '1.7.2'
      TERRAGRUNT_VERSION: '0.56.0'
      TERRAFORM_WORKING_DIR: ./applied/qa/org_create
      AWS_REGION: 'us-east-1'
    secrets: inherit




