name: KICS code Analysis

on:
  workflow_call:
    inputs:
      ENABLE_COMMENTS:
        description: "The enable comments could be true or false"
        required: true
        type: boolen

      WORKING_DIRECTORY:
        description: "The path to the configuration"
        required: true
        type: string
jobs:
  kics:
    name: Run KICS code Analysis
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
         ref: ${{ github.event.pull_request.head.ref }}

    - name: Run KICS scan
      uses: checkmarx/kics-github-action@v2.0.0
      with: 
        path: ${{ inputs.WORKING_DIRECTORY }}
        
        token: ${{ secrets.GITHUB_TOKEN }}
        output_path: myResults/
        ignore_on_exit: results
        enable_comments: ${{ inputs.ENABLE_COMMENTS }}  

    - name: Display KICS Results
      run: |
        cat myResults/results.json